In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plot
import mlp.data_providers as data_providers

In [95]:
batch_size = 100
data = data_providers.MNISTDataProvider(
    which_set = "valid", batch_size = 8, max_num_batches = 2, shuffle_order = True)
print(data.batch_size)
print(data.inputs.shape)

8
(10000, 784)


In [96]:
# Explain what is a class

class Snake:

    def __init__(self, name = 'dog', age = 10):
        self.name = name
        self.age = age

    def change_name(self, new_name):
        self.name = new_name
        
    def set_age(self, number):
        self.age = number
        self.oldage = number + 13
        
class Smoke:

    def __init__(self, name):
        self.name = name

    def change_name(self, new_name):
        self.name = new_name
        
    def set_age(self, number):
        self.age = number
        

# 对象=属性attribute（特征）+方法method（行为）
# 类：在python中，把具有相同属性和方法的对象归为一个类（class）

# 设置class时给 name 和 age 设定了默认值。
# 如果没有设置直接 a = Snake() 会报错：__init__() missing 2 required positional arguments: 'name' and 'age'
a = Snake()
print(a.name, a.age)
a = Snake(name = "python", age = 5) 
print(a.name, a.age)

a = Snake(name = "python", age = 5) 
b = Smoke(name = "r")
print(a)

# a是一个Snake object，里面有attribute name 和 attribute age，method change_name 和 method set_age。self就是a了

# method change_name 把attribute name的值改成new_name的值，无论这个attribute是否来自Snake
print(a.name)
Snake.change_name(self = b, new_name = "fef")
print(b.name)
a.change_name(new_name = "aba") # method change_name 把 a 的 attribute name 的值改成了new_name的值
print(type(a.change_name))
print(a.name)

# method set_age 把attribute age的值改成number的值
print(a.age)
# class中已经设置了a含有attribute age。因此这里是直接给attribute age 赋值令其等于10
a.age = 10 
print(a.age)

a.set_age(number = 20)
print(a.age, a.oldage)

# 如果class中没有设置a含有attribute oldage，那此时的赋值会影响接下来的method
a.oldage = 30
print(a.oldage)

dog 10
python 5
python
fef
<class 'method'>
aba
5
10
20 33
30


In [126]:
# how to find the path of the data

import os
print(os.environ['MLP_DATA_DIR'])
data_path = os.path.join(os.environ['MLP_DATA_DIR'], 'mnist-{2}.npz'.format("train", "valid", "test")) 
#0-train, 1-valid, 2-test
print(data_path)
print(os.path.isfile(data_path))

print('-{1}{0} {1}'.format("hello", "world"))  # 设置指定位置

# what is the slice()

a = slice(10)
print(a)
b = list(range(20,40))
print(b)
print(b[a])
print(b[slice(1,5,3)]) #从第2个到第6个，不包括第6个，每隔2个取一个。取出第2个和第5个
b = np.array([[list(range(20))], [list(range(20,40))]])
print(b)
print(b[slice(2)])

/Users/ljs/mlpractical/data
/Users/ljs/mlpractical/data/mnist-test.npz
True
-worldhello world
slice(None, 10, None)
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[21, 24]
[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]]
[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]]


In [97]:
# how to open the npz file

data = np.load(data_path)
print(data.files, data['inputs'].shape, data['targets'].shape) #train有50000个，valid有10000个，test有10000个
print(data['inputs'])
print(data['targets'])

print(data['inputs'][1])

['inputs', 'targets'] (10000, 784) (10000,)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[7 2 1 ... 4 5 6]
[0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.4531  0.4883  0.668   0.996   0.996
 0.586   0.3633  0.      0.    