In [1]:
import numpy as np

In [13]:
# output dim is 3, 2 batch
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[2,3,4], [5,6,8]])
c = (a-b) ** 2
print(c)
print(np.sum(c)) # (-1)**2 * 5 + (-2)**2
print(np.sum(c, 0))
print(np.sum(c,1))

[[1 1 1]
 [1 1 4]]
9
[2 2 5]
[3 6]
